'use client';
import {useRef,useState} from 'react';
import {ArrowUpRight,Download,Plus,Upload,Vote} from 'lucide-react';
import type {HausRoom} from '@/lib/community';
import type {Coin,SiteDesign} from '@/lib/haus-data';
import {SitePreview} from './site-preview';
import './community-panels.css';
const short=(wallet:string)=>wallet.slice(0,4)+'…'+wallet.slice(-4);
export function CommunityPitches({coin,room,wallet,loading,error,onCreate,onView,onVote}:{coin:Coin;room:HausRoom;wallet:string;loading:boolean;error:string;onCreate:()=>void;onView:(design:SiteDesign)=>void;onVote:(id:string)=>Promise<void>}){
 const [busy,setBusy]=useState('');const round=room.rounds.find(r=>r.status==='open');
 return <><div className="haus-tool-heading"><h2>Community pitches <span>{room.pitches.length}</span></h2><button className="button secondary" onClick={onCreate}><Plus size={15}/>New site</button></div>
 <div className="community-round"><div><strong>{round?'Voting is open':'Build the next community site'}</strong><p>{round?'Closes '+new Date(round.closesAt).toLocaleString()+'. '+Object.keys(round.votes).length+' holders voted.':'The first pitch opens a one-hour round.'}</p><small>One vote per verified wallet. At least 3 voters and more than half of all votes publish a site. Otherwise, the current site stays.</small></div>{room.publishedPitchId&&<a className="button secondary" href={'/sites/'+coin.mint} target="_blank" rel="noreferrer">Open live site <ArrowUpRight size={14}/></a>}</div>
 {error?<p role="alert">{error}</p>:loading?<div className="haus-empty">Loading pitches…</div>:room.pitches.length?<div className="haus-pitches">{[...room.pitches].reverse().map(p=>{
 const r=room.rounds.find(value=>value.id===p.roundId),votes=Object.values(r?.votes||{}).filter(id=>id===p.id).length,selected=r?.votes[wallet]===p.id,open=r?.status==='open'&&Date.parse(r.closesAt)>Date.now();
 return <article key={p.id}><div className="haus-pitch-preview"><SitePreview compact coin={coin} design={p.design}/></div><div className="haus-pitch-meta"><span>By {short(p.wallet)}</span><button className="text-button" onClick={()=>onView(p.design)}>View design <ArrowUpRight size={13}/></button></div><div className="community-vote"><span>{votes} {votes===1?'vote':'votes'} · {room.publishedPitchId===p.id?'Live site':open?'Voting open':'Closed'}</span>{open&&<button className={selected?'button primary':'button secondary'} aria-pressed={selected} disabled={!!busy} onClick={async()=>{setBusy(p.id);try{await onVote(p.id);}finally{setBusy('');}}}>{busy===p.id?'Saving…':selected?'Your vote':'Vote for site'}</button>}</div></article>;
 })}</div>:<div className="haus-empty"><Vote size={32}/><h3>THE FIRST MOVE IS YOURS.</h3><p>Pitch a website. Let the holders decide.</p><button className="button dark" onClick={onCreate}>Make a website <ArrowUpRight size={15}/></button></div>}
 <p className="haus-footnote">You can change your vote before the deadline. Pitches are fixed once submitted. Votes are checked against holdings when cast; one wallet does not necessarily mean one person.</p></>;
}
export function CommunityAssets({coin,room,loading,error,onUpload}:{coin:Coin;room:HausRoom;loading:boolean;error:string;onUpload:(file:File)=>Promise<boolean>}){
 const input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 return <div className="community-assets"><div className="haus-tool-heading"><h2>Shared assets <span>{room.assets.length}</span></h2><Upload size={22}/></div><form className="community-upload" onSubmit={async e=>{e.preventDefault();if(!file||busy)return;setBusy(true);try{if(await onUpload(file)){setFile(null);if(input.current)input.current.value='';}}finally{setBusy(false);}}}><label>Share artwork with the Haus<input ref={input} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>PNG, JPEG, WebP or GIF · up to 4 MB. Upload artwork you have permission to share. Anyone can download it.</small></label><button className="button primary" disabled={!file||busy}>{busy?'Uploading…':'Upload asset'}<Upload size={15}/></button></form>
 {error?<p role="alert">{error}</p>:loading?<p>Loading assets…</p>:room.assets.length?<div className="community-asset-grid">{[...room.assets].reverse().map(asset=>{const url='/api/haus/assets?mint='+coin.mint+'&id='+asset.id;return <article key={asset.id}><img src={url} alt={asset.name} loading="lazy"/><div><strong>{asset.name}</strong><small>{short(asset.wallet)} · {(asset.size/1024).toFixed(0)} KB</small><a className="button secondary" href={url+'&download=1'} download={asset.name}>Download <Download size={14}/></a></div></article>;})}</div>:<p className="haus-footnote">No shared assets yet. Verified holders can upload the first one.</p>}</div>;
}
