'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Search,Menu,X,Info} from 'lucide-react';
import {docs} from '@/lib/docs-content';
import {HausMark} from './haus-mark';
import {HowItWorks} from './how-it-works';
import {SiteFooter} from './site-footer';
import './docs.css';
export function DocsPage(){
 const [selected,setSelected]=useState('introduction'),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[how,setHow]=useState(false),[heading,setHeading]=useState(0);
 const scroll=useRef<HTMLDivElement>(null);const index=docs.findIndex(d=>d.id===selected),doc=docs[index]||docs[0];
 useEffect(()=>{function sync(){const id=location.hash.slice(1).split('/')[0];if(docs.some(d=>d.id===id))setSelected(id);}sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 useEffect(()=>{scroll.current?.scrollTo({top:0});setHeading(0);},[selected]);
 function choose(id:string){setSelected(id);setMenu(false);setQuery('');history.pushState({},'',`/docs#${id}`);}
 const results=docs.filter(d=>`${d.title} ${d.intro} ${d.blocks.map(b=>b.title+' '+b.paragraphs.join(' ')+' '+b.steps?.join(' ')).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 function track(){const pane=scroll.current;if(!pane)return;const tops=Array.from(pane.querySelectorAll<HTMLElement>('[data-doc-block]'));let current=0;tops.forEach((el,i)=>{if(el.getBoundingClientRect().top-pane.getBoundingClientRect().top<180)current=i;});setHeading(current);}
 return <div className="docs-shell"><a className="docs-skip" href="#docs-article">Skip to content</a><header className="docs-header"><a href="/" className="brand" aria-label="HAUS home"><HausMark/><span>haus</span></a><span className="docs-header-label">Documentation</span><nav aria-label="Main navigation"><a href="/">Explore</a><a href="/?view=saved">Saved</a><a href="/?view=hauses">My Hauses</a></nav><a className="docs-back" href="/">Open app <ArrowUpRight size={15}/></a><button className="docs-menu" aria-label={menu?'Close documentation menu':'Open documentation menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <div className="docs-layout"><aside className={`docs-sidebar ${menu?'is-open':''}`} aria-label="Documentation navigation"><div className="docs-sidebar-title"><BookOpen size={17}/>HAUS Docs</div><label className="docs-search"><Search size={15}/><input aria-label="Search documentation" placeholder="Search documentation…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={13}/></button>}</label><nav aria-label="Documentation sections">{[...new Set(docs.map(d=>d.group))].map(group=><div className="docs-nav-group" key={group}><h2>{group}</h2>{results.filter(d=>d.group===group).map(d=><a href={`#${d.id}`} aria-current={selected===d.id?'page':undefined} key={d.id} onClick={e=>{e.preventDefault();choose(d.id);}}>{d.title}</a>)}</div>)}{!results.length&&<p className="docs-no-results" role="status">No results for “{query}”. Try wallet, website or launch.</p>}</nav><div className="docs-sidebar-bottom">Built by holders.<br/><a href="/">Back to HAUS <ArrowUpRight size={12}/></a></div></aside>
 <div className="docs-scroll" ref={scroll} onScroll={track}><div className="docs-reading-layout"><main id="docs-article" tabIndex={-1} className="docs-article"><div className="docs-breadcrumb">Docs <span>/</span> {doc.group}</div><h1>{doc.title}</h1><p className="docs-intro">{doc.intro}</p>{selected==='introduction'&&<div className="docs-quick-links"><button onClick={()=>choose('holder-access')}><span>Participate</span><strong>Verify your holdings <ArrowUpRight size={16}/></strong></button><button onClick={()=>choose('website')}><span>Create</span><strong>Build a website <ArrowUpRight size={16}/></strong></button></div>}
 {doc.blocks.map((b,i)=><section data-doc-block id={`section-${i}`} key={b.title}><h2><a href={`#${doc.id}`} onClick={e=>{e.preventDefault();document.getElementById(`section-${i}`)?.scrollIntoView({behavior:'smooth',block:'start'});}}>{b.title}</a></h2>{b.paragraphs.map(p=><p key={p}>{p}</p>)}{b.steps&&<ol className="docs-steps">{b.steps.map(s=><li key={s}>{s}</li>)}</ol>}{b.note&&<aside className="docs-note"><Info size={18}/><p>{b.note}</p></aside>}</section>)}
 <div className="docs-article-meta">Applies to the current HAUS build. Feature availability is described in each guide.</div><nav className="docs-pager" aria-label="Previous and next guide">{index>0?<button onClick={()=>choose(docs[index-1].id)}><span><ArrowLeft size={13}/>Previous</span><b>{docs[index-1].title}</b></button>:<div/>}{index<docs.length-1&&<button onClick={()=>choose(docs[index+1].id)}><span>Next<ArrowRight size={13}/></span><b>{docs[index+1].title}</b></button>}</nav></main><aside className="docs-toc"><h2>On this page</h2>{doc.blocks.map((b,i)=><button key={b.title} className={heading===i?'active':''} onClick={()=>document.getElementById(`section-${i}`)?.scrollIntoView({behavior:'smooth',block:'start'})}>{b.title}</button>)}<a href="/">Explore HAUS <ArrowUpRight size={13}/></a></aside></div><SiteFooter onHow={()=>setHow(true)}/></div></div>{how&&<HowItWorks onClose={()=>setHow(false)} onStart={()=>{location.href='/';}}/>}</div>;
}
