export type DocSection={id:string;group:string;title:string;intro:string;blocks:{title:string;paragraphs:string[];steps?:string[];note?:string}[]};
export const docs:DocSection[]=[
 {id:'introduction',group:'Get started',title:'Welcome to HAUS',intro:'A coin brings people together. A Haus gives them a place to build.',blocks:[
  {title:'What is a Haus?',paragraphs:['HAUS combines token discovery with a shared workspace for each listed coin. Start with the market, enter the coin’s Haus, and use its website studio, project resources, community pitches and holder chat.','The product is organized around the token. Tools belong to a specific Haus, so the coin you are viewing determines the community, artwork, links and website you work on.']},
  {title:'The three places to start',paragraphs:['Explore is the discovery page. Saved is your device-local watchlist. My Hauses brings together the communities you have successfully verified into with the connected wallet on this device.','How it works provides a short introduction. These docs explain the full workflow and distinguish working features from features that are not yet connected.']},
  {title:'Your first visit',paragraphs:[],steps:['Open Explore and choose a coin.','Review its chart, contract address and available market information.','Select Enter Haus to browse its tools and public conversation.','Connect your wallet and verify holdings when you want to participate.'],note:'Browsing does not require a wallet. Saving a coin does not verify holdings or join its Haus.'}
 ]},
 {id:'discovery',group:'Get started',title:'Explore & Saved',intro:'Find a coin, check its identity, and keep the ones you care about close.',blocks:[
  {title:'Find and filter coins',paragraphs:['Search by token name, ticker or contract address. Trending sorts by volume; New sorts by launch time. About to graduate selects ungraduated coins with reported bonding progress of at least 80%. Graduated selects migrated tokens.','Use the sort menu to change the ordering and the grid/list controls to change the layout. Explore currently shows the configured token registry, not every token on Solana.']},
  {title:'Read the token page',paragraphs:['A coin opens its own market page with identity, contract address, price and available market metrics. The chart has interval controls, volume and zoom. Trades, Holders and About provide additional context beneath it.','Use the contract address to distinguish tokens with similar names. External trading and explorer links open the relevant third-party service.']},
  {title:'Build a watchlist',paragraphs:['Use the bookmark control on a token page to add or remove it from Saved. Saved coins are stored in this browser. They do not sync to another device and do not depend on a wallet.','Clearing browser site data removes the watchlist. Removing a bookmark does not sell a token or change your wallet holdings.']}
 ]},
 {id:'my-hauses',group:'Get started',title:'My Hauses',intro:'A shortcut back to the communities you have participated in.',blocks:[
  {title:'How a Haus appears here',paragraphs:['After a successful holdings verification, HAUS remembers that token under the connected wallet on this device. Connect that wallet and open My Hauses to return to its communities.','This is a local history of successful verification, not a live portfolio scan. Communities verified before this feature was added may need another verification to appear.']},
  {title:'Returning to a community',paragraphs:['Select a Haus to open its overview. Your saved membership shortcut does not restore an authorization session. Verify again inside the Haus when asked to contribute.','Switching wallets changes the list. Clearing site storage removes these shortcuts, but does not alter balances or erase public messages and pitches.']}
 ]},
 {id:'holder-access',group:'The workspace',title:'Wallet & holder access',intro:'Public browsing, with participation reserved for verified holders.',blocks:[
  {title:'Verify your wallet',paragraphs:[],steps:['Select Verify holdings inside a token’s Haus.','Connect a Solana wallet that supports message signing.','Sign the verification message presented by your wallet.','HAUS checks that the wallet owns a positive balance of that token on Solana mainnet.'],note:'Holder verification signs a message. It does not submit a transaction or transfer tokens.'},
  {title:'What verification unlocks',paragraphs:['A valid holder session allows participation in the room and submission of website pitches. The studio also requests verification for editing themes, saving drafts and exporting HTML. You can view the tools and previews as a guest.','Authorization is scoped to the wallet and token. Switching wallets, a session expiring, or a server restart can require verification again. Holdings are checked again for protected posting actions.']},
  {title:'When access is refused',paragraphs:['Confirm that you connected the wallet holding the exact token contract. A matching ticker alone is not enough. Newly acquired tokens may require a short wait before the RPC provider sees the confirmed balance.','If a wallet cannot sign messages, choose one that can. If verification reports a network error, retry later; connecting a wallet alone does not grant holder access.']}
 ]},
 {id:'workspace',group:'The workspace',title:'Navigate your Haus',intro:'One token workspace, with the conversation alongside your tools.',blocks:[
  {title:'Workspace tabs',paragraphs:['Overview brings together the community entry points and market summary. Website opens the studio. DEX tools shows the token profile and project links. Pitches contains community website submissions. Assets exposes the token’s artwork and identity. Chart returns to market analysis within the Haus.','Back to coin takes you to the standalone market page. The global Explore, Saved and My Hauses tabs are for moving between coins and communities.']},
  {title:'Keep the conversation in view',paragraphs:['The room stays alongside the tools while you switch workspace tabs. On smaller screens it docks beneath the workspace. Use its minimize/open control to give the tools more room.','Changing tools within the same Haus does not take you into another token’s chat. Entering a different Haus changes both the workspace and its conversation.']}
 ]},
 {id:'chat',group:'The workspace',title:'Team chat',intro:'A shared conversation for the people building around a token.',blocks:[
  {title:'Read and contribute',paragraphs:['Room messages are publicly readable. Verify holdings to send a message. Messages show the posting wallet and timestamp; your own posts are marked for you.','Press Enter to send and Shift + Enter for a new line. Messages can contain up to 1,000 characters. The room periodically refreshes and follows new messages when you are near the bottom.']},
  {title:'Visibility and storage',paragraphs:['A holder-only posting rule does not make the room private. Do not post seed phrases, private keys or information you expect to remain confidential.','The current service retains the latest 500 messages per token. Messages and pitches are stored by the HAUS server; availability depends on that service and its storage. Rapid successive contributions may be rate-limited.']}
 ]},
 {id:'website',group:'Build together',title:'Website studio',intro:'Give a coin a home using editable designs built around its identity.',blocks:[
  {title:'Create a design',paragraphs:[],steps:['Enter the coin’s Haus and choose Website.','Verify holdings to edit and contribute.','Choose Editorial, Terminal, Playful or After hours.','Edit the headline, tagline and story while reviewing the preview.','Save a local draft, export the HTML, or submit a pitch.']},
  {title:'Drafts and exports',paragraphs:['Save draft stores the current design on this device. Returning to that token’s studio in the same browser restores its saved draft. A draft is not automatically shared.','Export HTML downloads a website file. Exporting does not deploy a live website or register a domain. Referenced remote artwork still needs to remain available. Store an exported copy if you need a backup outside the browser.']},
  {title:'What the editor does today',paragraphs:['The studio uses four editable templates with the coin’s artwork and content. It is not an AI website generator. Headline and tagline fields allow up to 100 characters, and the story allows up to 500.','The local preview route can display a draft saved in the current browser. Sharing that route does not publish the draft for other visitors.'],note:'Hosted sites, automatic deployment and binding voting are not connected.'}
 ]},
 {id:'pitches',group:'Build together',title:'Community pitches',intro:'Share a website direction with the Haus and discuss it in the room.',blocks:[
  {title:'Submit and review',paragraphs:['From Website, select Pitch to the Haus with a valid holder session. A submitted pitch includes the design, wallet and submission time. It appears in the shared Pitches tab.','View design loads a pitch into the website studio for review. Discuss proposed changes in the room. Loading a design does not change the original shared submission.']},
  {title:'Current limits',paragraphs:['The current room accepts up to 50 pitches per token. Contributions are rate-limited to prevent rapid repeat posts.','Pitches are proposals for discussion. There is no connected binding vote, automatic winner selection or automatic publishing workflow. Submitting a pitch does not make it the token’s official website.']}
 ]},
 {id:'dex-assets',group:'Build together',title:'DEX tools & brand assets',intro:'Keep the token’s public identity and resources within reach.',blocks:[
  {title:'DEX tools',paragraphs:['View profile opens the token’s external market profile. Project links collect available website and social links, with a Pump.fun link for the token. External services manage their own pages and actions.','The shared funding panel is a preview of a future contribution flow. Contributions are unavailable and no deposit address is created. Selecting a displayed currency does not fund anything.']},
  {title:'Brand assets',paragraphs:['Assets shows the current token artwork, name, ticker and contract. Open artwork opens the source image, and Copy address copies the token mint.','Community uploads and an asset approval workflow are not connected. The displayed artwork is the currently configured token image; it is not a community-approved replacement.']}
 ]},
 {id:'launching',group:'Reference',title:'Launch a coin',intro:'Prepare your token details in the native HAUS launch form.',blocks:[
  {title:'Fill out the form',paragraphs:['Launch a coin in the header and Start a haus on Explore open the same form. Enter the token name, ticker, story and image. An initial buy in SOL is optional.','The name allows up to 32 characters; the ticker accepts up to 10 letters or numbers. The story allows up to 500 characters. Use PNG, JPEG or WebP artwork within the displayed 4 MB limit.']},
  {title:'Availability and wallet review',paragraphs:['The form remains available even when live launching is disconnected. Filling it out does not create a token. Live submission depends on the server’s launch configuration and readiness.','When enabled, the flow prepares the launch and presents a review before asking the wallet to approve a transaction. Read the initial buy, token amount, estimated wallet debit and creator-fee recipient before proceeding. The wallet shows the final transaction.'],note:'The launch form being visible is not confirmation that live token creation is enabled.'},
  {title:'Submission and confirmation',paragraphs:['A submitted transaction may take time to confirm. HAUS keeps pending launch details in the current browser session for the connected wallet and can resume checking them.','Only a confirmed success is shown as a live token. If the outcome is uncertain, inspect the transaction link before retrying. A disconnected wallet, rejected request or failed transaction is not a successful launch.']}
 ]},
 {id:'data-privacy',group:'Reference',title:'Market data & privacy',intro:'Understand where information comes from and what HAUS stores.',blocks:[
  {title:'Market sources',paragraphs:['Market reads use DEX Screener and Solana RPC. Candles and recent pool trades use GeckoTerminal. The market page refreshes periodically; chart and trade updates follow their own refresh cycles.','Provider delays and different refresh intervals can produce differences between displayed prices. Missing values are shown as unavailable rather than replaced with invented data. A chart illustrates trading activity; it is not a guarantee of liquidity or future value.']},
  {title:'Holder table coverage',paragraphs:['The holder endpoint resolves the largest token accounts via Solana RPC. This is not a complete holder directory or a wallet-aggregated ownership report. Pool and vault accounts can appear.','Public RPC providers may rate-limit holder reads. Retry states indicate a data problem, not proof that the token has no holders.']},
  {title:'Storage and external connections',paragraphs:['Saved coins, website drafts and My Hauses shortcuts live in browser storage. Pending launch recovery uses browser session storage. Public messages and pitches are stored by the server.','Wallet connections are handled through the wallet provider. HAUS does not require your seed phrase or private key. Market requests, external artwork and links involve third-party services with their own privacy practices.','Clearing local storage removes local preferences and drafts; it does not delete public contributions, reverse transactions or change wallet balances.']}
 ]},
 {id:'troubleshooting',group:'Reference',title:'Troubleshooting',intro:'Practical checks for the most common issues.',blocks:[
  {title:'My Haus is missing',paragraphs:['Connect the same wallet and use the same browser where you verified. My Hauses remembers successful verification on this device; it does not scan your full portfolio. Open the token from Explore and verify again to add its shortcut.']},
  {title:'I can browse but cannot interact',paragraphs:['Connect your wallet, then verify holdings inside the specific Haus. Confirm that the wallet holds a positive balance of the exact token on Solana mainnet. Reverify if the session expired or the wallet changed.']},
  {title:'A chart, table or room will not load',paragraphs:['Use the relevant Retry or refresh control. Check your connection and allow time for provider rate limits to clear. Market, chart and community services can fail independently; one unavailable panel does not imply all features are down.']},
  {title:'My draft disappeared',paragraphs:['Check the token, browser and device. Only saved drafts persist after leaving the studio. Clearing site storage, using private browsing or switching devices can remove access to local drafts. Keep an HTML export for an independent copy.']},
  {title:'I cannot launch or publish',paragraphs:['The launch form can be used before live submission is configured. An unavailable launch cannot be completed by reconnecting a wallet alone. Website hosting and automatic publishing are separate features and are not currently connected.']}
 ]}
];
