import sys, json, base64, html
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent / '.fonttools'))
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.transformPen import TransformPen
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'public/brand-kit/article-images'
OUT.mkdir(parents=True, exist_ok=True)
K, P, PALE, PAPER = '#191919', '#f2a8cd', '#f8d4e5', '#f4f0e9'
fonts = {k: TTFont(str(p)) for k,p in {
    'bold': 'C:/Windows/Fonts/Anton-Regular.ttf',
    'sans': 'C:/Windows/Fonts/arial.ttf',
    'script': ROOT/'public/fonts/HVSMEGS-Style1.otf'
}.items()}

def rect(x,y,w,h,fill,stroke='none',r=4):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}" fill="{fill}" stroke="{stroke}"/>'

def text(s,x,y,w,h=24,f='sans',color=K):
    font=fonts[f]; glyphs=font.getGlyphSet(); cmap=font.getBestCmap()
    pen=SVGPathPen(glyphs); bounds=BoundsPen(glyphs); offset=0
    for char in s:
        g=glyphs[cmap[ord(char)]]; tr=(1,0,0,-1,offset,0)
        g.draw(TransformPen(pen,tr)); g.draw(TransformPen(bounds,tr)); offset+=g.width
    a,b,c,d=bounds.bounds; scale=min(w/(c-a),h/(d-b))
    return f'<g aria-label="{html.escape(s)}" data-name="{html.escape(s)}"><path d="{pen.getCommands()}" fill="{color}" transform="translate({x} {y}) scale({scale}) translate({-a} {-b})"/></g>'

def mark(x,y,s=.12):
    return f'<path transform="translate({x} {y}) scale({s})" d="M22 31 195 0 150 141H302L250 282H165L178 181H136L103 282H0Z" fill="{K}"/>'

def base():
    grid=''.join(f'M{x} 0V900' for x in range(32,1600,100))+''.join(f'M0 {y}H1600' for y in range(34,900,100))
    return rect(0,0,1600,900,'white',r=0)+f'<path d="{grid}" fill="none" stroke="{K}" opacity=".085" stroke-width="1.25"/>'+f'<g opacity=".035">{text("Haus",-350,45,2050,1100,"script")}</g>'+mark(72,62)+text('HAUS',120,62,80,34,'bold')

def footer(note='PRODUCT PREVIEW / NOT LIVE YET'):
    return rect(72,790,212,52,K)+text('@hausdotfun',96,807,166,20,color='white')+rect(296,790,157,52,P)+text('haus.fun',320,807,110,20)+text(note,1040,817,485,14,color='#706d68')

def screenshot(name, x,y,w,h,crop=None):
    source=ROOT/'docs/screenshots'/name; raw=source.read_bytes()
    mime='image/png' if raw[:8]==b'\x89PNG\r\n\x1a\n' else 'image/jpeg'
    iw,ih=Image.open(source).size
    view=crop or (0,0,iw,ih)
    return f'<svg x="{x}" y="{y}" width="{w}" height="{h}" viewBox="{" ".join(map(str,view))}" preserveAspectRatio="xMidYMin slice" overflow="hidden"><image width="{iw}" height="{ih}" href="data:{mime};base64,{base64.b64encode(raw).decode()}"/></svg>'

def browser(id,x,y,w,h,body,angle=-3):
    return f'<g id="{id}" transform="translate({x} {y}) rotate({angle} {w/2} {h/2})">'+rect(0,0,w,h+40,PAPER,'#d4d0ca')+rect(0,0,w,40,'#f5f3f0')+''.join(f'<circle cx="{v}" cy="20" r="3" fill="#c8c4be"/>' for v in [20,33,46])+text('app.haus.fun',w/2-65,13,130,14,color='#76716d')+body+'</g>'

def arrow(x,y,w=40):
    return f'<path d="M{x} {y}h{w}m-10 -8 10 8 -10 8" fill="none" stroke="{K}" stroke-width="2"/>'

def svg(title,body):
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900" overflow="hidden" role="img" aria-label="{title}"><title>{title}</title>{base()}{body}</svg>'

# Real, saved Explore interface; no generated trading activity.
one=text('EVERY COIN',72,234,510,110,'bold')+text('NEEDS A',72,365,455,110,'bold')+text('Haus.',64,473,484,176,'script',P)
one+=text('A coin brings people together.',76,671,470,24)+text('Give them somewhere to build.',76,712,470,24)
one+=browser('explore-interface',640,146,1050,604,screenshot('haus-discovery-controls.png',0,40,1050,604),-4)
one+=footer()

# Crop the saved studio to emphasize the tools and adjacent conversation.
two=text('BUILT BY',72,221,475,111,'bold')+text('ITS HOLDERS.',72,352,485,111,'bold')+text('together.',66,460,475,142,'script',P)
two+=text('Create. Discuss. Contribute.',76,660,450,24)+text('One workspace for your community.',76,701,474,24)
two+=browser('studio-and-holder-chat',627,151,1000,605,screenshot('haus-studio-chat.png',0,40,1000,605,(48,245,1320,790)),-3)
two+=footer()

# UI-styled explanatory diagram, with the real unavailable vault state below.
three=text('SHARED RESOURCES.',72,160,1120,89,'bold')+text('Shared decisions.',72,262,990,115,'script',P)
three+=rect(1261,72,267,39,PALE)+text('IN DEVELOPMENT',1282,84,225,14)
for x,n,label,detail in [(72,'01','CREATOR FEES','Generated by the token'),(575,'02','TOKEN VAULT','Held for a community decision'),(1078,'03','HOLDER VOTE','Decide how fees are allocated')]:
    three+=rect(x,420,450,147,PAPER,'#d4d0ca')+rect(x+20,440,39,29,P)+text(n,x+31,449,19,11)
    three+=text(label,x+78,442,345,34,'bold')+text(detail,x+24,513,402,20)
three+=arrow(532,491,32)+arrow(1035,491,32)
three+=rect(72,601,705,142,K)+text('FEES STAY IN THE VAULT',100,626,640,32,'bold','white')+text('until an allocation is approved.',100,683,620,24,color='white')
three+=rect(808,601,720,142,PAPER,'#d4d0ca')+text('PLANNED ALLOCATION OPTIONS',832,623,640,15,color='#706d68')
three+=text('Keep in vault / Holder rewards',832,661,660,22)+text('Creator allocation',832,701,660,22)
three+=footer('PLANNED SYSTEM / VOTING RULES IN DEVELOPMENT')

designs=[
    ('image-1-haus-overview','IMAGE 1','Every coin needs a Haus','Place after the opening introduction, before WE ARE THE DEVS.',svg('Every coin needs a Haus',one)),
    ('image-2-built-by-holders','IMAGE 2','Built by its holders','Place after FROM HOLDERS TO BUILDERS, before A SAY IN WHAT COMES NEXT.',svg('Built by its holders',two)),
    ('image-3-token-vault','IMAGE 3','Shared resources. Shared decisions.','Place after A SAY IN WHAT COMES NEXT, before BUILT BY THE ONES WHO STAY.',svg('Shared resources. Shared decisions.',three)),
]
for slug,label,title,placement,art in designs:
    (OUT/f'{slug}.svg').write_text(art,encoding='utf-8')
    (OUT/f'{slug}.html').write_text(f'<!doctype html><html><head><meta charset="utf-8"><title>{label} - {title}</title><style>body{{margin:0;background:white}}svg{{display:block}}</style></head><body>{art}</body></html>',encoding='utf-8')

cards=''.join(f'<section id="image-{i+1}"><div class="caption"><div><b>{label}</b><h2>{title}</h2><p>{placement}</p></div><nav><a href="{slug}.html">Artwork HTML</a><a href="{slug}.svg" download>Download SVG</a><a href="{slug}.png" download>Download PNG</a></nav></div><div class="art">{art}</div></section>' for i,(slug,label,title,placement,art) in enumerate(designs))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HAUS — Article images 1, 2 & 3</title><style>
*{box-sizing:border-box}body{margin:0;background:#e9e5e1;color:#191919;font:15px Arial,sans-serif}main{max-width:1664px;margin:auto;padding:40px 32px}header{padding:10px 0 34px}h1{font-size:38px;letter-spacing:-1.4px;margin:12px 0}header p{max-width:950px;line-height:1.6;color:#625b58}section{margin-bottom:64px;scroll-margin:20px}.caption{display:flex;align-items:end;justify-content:space-between;gap:24px;padding-bottom:20px}.caption b{display:inline-block;background:#191919;color:white;font-size:13px;letter-spacing:2px;padding:9px 12px}h2{font-size:24px;margin:12px 0 7px}p{margin:0;line-height:1.6;color:#625b58}nav{display:flex;gap:10px;flex-wrap:wrap}a{color:inherit;text-decoration:none;padding:11px 14px;background:#f8d4e5;border-radius:4px;font-size:13px;white-space:nowrap}.art>svg{display:block;width:100%;height:auto}aside{padding:24px;background:#faf9f7;line-height:1.7}aside p+p{margin-top:12px}@media(max-width:800px){main{padding:20px 12px}.caption{display:block}nav{margin-top:16px}h1{font-size:30px}}@media print{header,.caption,aside{display:none}main{padding:0}section{break-after:page;margin:0}}
</style></head><body><main><header><small>HAUS / ARTICLE GRAPHICS</small><h1>Three images. In article order.</h1><p>Each graphic is 1600 × 900. Open an individual Artwork HTML page for a clean import, or download its SVG for Figma. Headlines, branding, backgrounds, and the vault diagram are vector paths and shapes; the actual product captures in Images 1 and 2 remain embedded images.</p></header>'''+cards+'''<aside><strong>Export & source notes</strong><p>The labels IMAGE 1, IMAGE 2, and IMAGE 3 are outside the artwork, so they won’t appear in the exported graphics. Each standalone HTML and SVG is self-contained. Lettering is outlined for reliable Figma import.</p><p>Images 1 and 2 use saved project screenshots, not newly captured live pages. Image 1: haus-discovery-controls.png. Image 2: haus-studio-chat.png, cropped to the studio and chat. Image 3 is an explanatory vector diagram based on the planned vault flow, not a screenshot of live voting. No balances, votes, or user messages have been fabricated.</p></aside></main></body></html>'''
(OUT/'index.html').write_text(page,encoding='utf-8')
(OUT/'manifest.json').write_text(json.dumps({'size':[1600,900],'images':[{'file':x[0],'label':x[1],'placement':x[3]} for x in designs],'sources':['haus/docs/screenshots/haus-discovery-controls.png','haus/docs/screenshots/haus-studio-chat.png','haus/components/vault-panel.tsx'],'type':'Outlined vector graphics with embedded actual UI captures'},indent=2),encoding='utf-8')
print(f'Created 3 SVGs, 3 standalone HTML files and labeled gallery: {OUT}')
